const routeName = {
  onboarding: {
    spash: 'SplashScreen',
    locale: 'LocaleScreen',
    screen1: 'OnboardingScreen1',
    screen2: 'OnboardingScreen2',
    screen3: 'OnboardingScreen3',
    screen4: 'OnboardingScreen4',
    screen5: 'OnboardingScreen5',
    home: 'HomeScreen',
  },
  auth: {
    registerOrSignin: 'RegisterOrSignInScreen',
    login: 'LoginScreen',
    signup: 'SignUpScreen',
    registerName: 'registerNameScreen',
    registerPro: 'registerProScreen',
    registerStep2: 'RegisterStep2',
    registerStep3: 'RegisterStep3',
    forgotPassword: 'ForgotPasswordScreen',
    code: 'CodeScreen',
    newPassword: 'NewPasswordScreen',
    welcome: 'Welcome',
    cgv: 'CgvScreen',
    privacy: 'PrivacyScreen',
  },
  tab: {
    base: 'Tab',
    mag: {
      base: 'Mag',
      home: 'MagScreen',
      article: 'ArticleScreen',
      story: 'Storycreen',
    },
    inspiration: {
      base: 'Inspiration',
      home: 'InspirationScreen',
      detail: 'InspirationDetailScreen',
      destination: 'InspirationDestinationScreen',
    },
    address: {
      base: 'Address',
      home: 'AddressScreen',
      detail: 'AddressDetailScreen',
      card: 'AddressCardScreen',
    },
    map: {
      base: 'Map',
      home: 'MapScreen',
    },
    favorite: {
      base: 'Favorite',
      home: 'FavoriteScreen',
      detail: 'DetailScreen',
    },
  },
  user: {
    base: 'User',
    chat: 'ChatScreen',
    profile: {
      home: 'ProfileScreen',
      info: 'InfoPersoScreen',
      tags: 'ProfileTagsScreen',
      changeEmail: 'ChangeEmailScreen',
      changePassword: 'ChangePasswordScreen',
    },
    notification: 'NotificationScreen',
    secret: 'SecretScreen',
    membership: 'MembershipScreen',
    travel: {
      home: 'TravelScreen',
      date: 'TravelDateScreen',
      place: 'TravelPlaceScreen',
    },
    service: {
      home: 'ServiceScreen',
      orders: 'ServiceOrdersScreen',
      orderDetail: 'ServiceOrderDetailScreen',
      item: 'ServiceItemScreen',
      condition: 'ServiceConditionScreen',
      contact: 'ServiceContactScreen',
      creneau: 'ServiceCreneauScreen',
      date: 'ServiceDateScreen',
      duration: 'ServiceDurationScreen',
      place: 'ServicePlaceScreen',
      resume: 'ServiceResumeScreen',
    },
  },
  others: {
    base: 'Others',
    whoGigi: 'WhoGigiScreen',
    cgv: 'CgvScreen',
    privacy: 'PrivacyScreen',
  },
};

export default routeName;
