const routeName = {
  onboarding: {
    spash: 'SplashScreen',
    locale: 'LocaleScreen',
    screen1: 'OnboardingScreen1',
    screen2: 'OnboardingScreen2',
    screen3: 'OnboardingScreen3',
    screen4: 'OnboardingScreen4',
    screen5: 'OnboardingScreen5',
    home: 'HomeScreen',
  },
  auth: {
    registerOrSignin: 'RegisterOrSignInScreen',
    login: 'LoginScreen',
    signup: 'SignUpScreen',
    registerName: 'registerNameScreen',
    registerPro: 'registerProScreen',
    registerStep2: 'RegisterStep2',
    registerStep3: 'RegisterStep3',
    forgotPassword: 'ForgotPasswordScreen',
    code: 'CodeScreen',
    newPassword: 'NewPasswordScreen',
    welcome: 'Welcome',
    cgv: 'CgvScreen',
    privacy: 'PrivacyScreen',
  },
  tab: {
    base: 'Tab',
    mag: {
      base: 'magBase',
      home: 'mag',
      article: 'article',
      story: 'story',
    },
    inspiration: {
      base: 'inspirationBase',
      home: 'inspirations',
      detail: 'inspirationsDetail',
      destination: 'destination',
    },
    address: {
      base: 'addressBase',
      home: 'notebooks',
      detail: 'addressDetail',
      card: 'addressCard',
    },
    map: {
      base: 'mapBase',
      home: 'maps',
    },
    favorite: {
      base: 'favoriteBase',
      home: 'favorites',
      detail: 'favoriteDetail',
    },
  },
  user: {
    base: 'userBase',
    chat: 'chat',
    profile: {
      home: 'profile',
      info: 'infoperso',
      tags: 'tags',
      changeEmail: 'email',
      changePassword: 'password',
    },
    notification: 'notifications',
    secret: 'SecretScreen',
    membership: 'membership',
    travel: {
      home: 'travels',
      date: 'TravelDateScreen',
      place: 'TravelPlaceScreen',
    },
    service: {
      home: 'services',
      orders: 'ServiceOrdersScreen',
      orderDetail: 'ServiceOrderDetailScreen',
      item: 'ServiceItemScreen',
      condition: 'ServiceConditionScreen',
      contact: 'ServiceContactScreen',
      creneau: 'ServiceCreneauScreen',
      date: 'ServiceDateScreen',
      duration: 'ServiceDurationScreen',
      place: 'ServicePlaceScreen',
      resume: 'ServiceResumeScreen',
    },
  },
  others: {
    base: 'Others',
    whoGigi: 'WhoGigiScreen',
    cgv: 'CgvScreen',
    privacy: 'PrivacyScreen',
  },
};

export default routeName;
