import UserStateType from './type';

export const userInitialState: UserStateType = {
  authInfo: {
    current_user: null,
    csrf_token: '',
    logout_token: '',
    access_token: '',
    refresh_token: ''
  },
  userInfo: {
    id: '',
    addressZipcode: '',
    addressCity: '',
    addressStreet: '',
    addressCountryCode: '',
    civility: {
      id: '',
      label: '',
    },
    label: '',
    langcode: '',
    lastName: '',
    firstName: '',
    birthdate: {
      timestamp: '',
      label: '',
    },
    isPro: false,
    isScheduledDeletion: false,
    proActivity: {
      id: '',
      label: '',
    },
    profiles: [],
    whishes: [],
    phoneNumber: '',
    profilePicture: {
      urlLq: '',
      urlHq: '',
    },
    email: '',
    godfather: {
      email: '',
    },
    notifyNewContent: false,
    notifyOffersSubscription: false,
    notifyInspirationsCommunity: false,
    notifyNews: false,
    notifyOrderInfo: false,
    notifyEmail: false,
    notifications: {},
    roles: [],
  },
  tag: {
    profile: [],
  },
  userLists: [],
  persoInfosDatas: {
    translation: {
      cancelDeleteAccountSaveButtonLabel: '',
      deleteAccountTitle: '',
      deleteAccountMessage: '',
      deleteAccountSaveButtonLabel: '',
      deleteMyAccountTitle: '',
      personnalInformation: '',
      addProfilePicture: '',
      changeProfilePicture: '',
      fromGallery: '',
      takeAPicture: '',
      civility: '',
      sir: '',
      madam: '',
      name: '',
      firstname: '',
      nickname: '',
      dateBirth: '',
      phoneNumber: '',
      email: '',
      editEmail: '',
      password: '',
      save: '',
      editMyEmail: '',
      newEmail: '',
      confirmNewEmail: '',
      saveNewEmail: '',
      editMyPassword: '',
      oldPassword: '',
      newPassword: '',
      confirmNewPassword: '',
      editPassword: '',
      newPasswordSaved: '',
      cancel: '',
      validate: '',
      profile: '',
      myTrips: '',
      myProfile: '',
      myDesires: '',
      edit: '',
      postalAddressInvoicing: '',
      addressStreetPlaceholder: '',
      addressCityPlaceholder: '',
      addressZipcodePlaceholder: '',
      addressCountryPlaceholder: '',
    },
  },
  travelDatas: {
    config: {
      travel: {
        thumbnail: {
          label: '',
          alt: '',
          urlHq: '',
          urlLq: '',
        },
      },
    },
    translation: {
      myTrips: '',
      dateFrom: '',
      dateTo: '',
      edit: '',
      travelAddButtonLabel: '',
      newTravel: '',
      newTravelSuccess: '',
      newTravelError: '',
      editTravel: '',
      editTravelSuccess: '',
      editTravelError: '',
      deleteTravel: '',
      deleteTravelSuccess: '',
      deleteTravelError: '',
      travelChooseRegionTitle: '',
      travelChooseRegionText: '',
      travelChooseDatesTitle: '',
      travelChooseDatesInput: '',
      travelChooseLabelTitle: '',
      travelConfirmDeleteText: '',
      save: '',
    },
  },
  serviceDatas: {
    phoneContactTypes: {
      items: [],
    },
    phoneNumbers: {
      items: [],
    },
    serviceProducts: {
      title: '',
      total: 0,
      items: [],
    },
    travelPurposes: {
      items: [],
    },
    translation: {
      gigissimoServices: '',
      gigissimoServicesDescription: '',
      priceStartingAt: '',

      details: '',
      termsAndConditions: '',
      bookAppointment: '',
      seeOthersServices: '',

      adviceAppointment: '',
      customisedJourney: '',
      conciergeService: '',
      orderDestinationLabel: '',
      orderDestinationDescription: '',

      servicesIntroTitle: '',
      servicesIntroDescription: '',
      helpMeOrganiseMyTrip: '',

      knowTravelDates: '',
      chooseYourDates: '',
      dontKnowTravelDates: '',
      dates: '',
      confirmDates: '',
      dateFrom: '',
      dateTo: '',
      next: '',

      orderContactMethodLabel: '',
      orderPhoneNumberLabel: '',
      selectRegionCode: '',

      appointmentCallslotLabel: '',
      showMoreSlots: '',

      orderSummaryLabel: '',
      edit: '',
      destination: '',
      travelDates: '',
      toBeContacted: '',
      yourSlot: '',
      day: '',
      days: '',
      person: '',
      people: '',
      confirmAndPay: '',
      longClickToChangeStartDate: '',

      yourTravelDetails: '',
      howManyPeopleTravelling: '',
      howManyPeoplePlaceholder: '',
      haveAccommodation: '',
      nameAccommodationLabel: '',
      stayPrioritiesLabel: '',

      yes: '',
      no: '',
      skipStep: '',

      conciergeServiceDurationLabel: '',
      conciergeServiceDurationPlaceholder: '',
      conciergeServiceDurationReachMaxDescription: '',
      conciergeServiceCorrespondingDateLabel: '',
      conciergeServiceTotalNumberOfDays: '',

      yourRequest: '',

      myOrders: '',
      noOrderYet: '',
      orderStatusOnDate: '',
      statusLabel: '',
      enableNotifications: '',
      servicesNotificationDescription: '',
      goToSettings: '',
      newOrder: '',

      adviceAppointmentExpertCalling: '',
      editAppointment: '',
      modifyMyOrder: '',
      showInvoice: '',
      download: '',
      confirmNewDate: '',
      confirmNewDateSuccess: '',
      confirmNewDateMaximumReached: '',

      customisedJourneyExplanation: '',
      conciergeServiceExplanation: '',

      orderThankYouTitle: '',
      orderThankYouMessage: '',
      orderThankYouSuccessMessage: '',
      close: '',
    },
  },
  serviceSteps: {
    startDate: '',
    endDate: '',
    region: {
      id: '',
      label: '',
    },
    hasHotel: false,
    hotel: '',
    nbPers: 1,
    priorities: [],
    contactType: {
      id: '',
      label: '',
    },
    phoneCode: '+33',
    phoneNumber: '',
    quantity: 1,
    callslot: {
      id: '',
      date: 0,
      label: '',
    },
    travel: {
      start: 0,
      end: 0,
    },
  },
  travels: {
    total: 0,
    items: [],
  },
};
