fastlane_version '2.225.0'

platform :ios do
    desc 'Fetch certificates and provisioning profiles'
    lane :certificates do
        match(app_identifier: 'fr.grazie.gigi', type: 'appstore', readonly: true)
    end

    desc 'Build the iOS application.'
    lane :build do
        increment_build_number(xcodeproj: './ios/Grazie.xcodeproj')
        gym(
            scheme: 'Grazie',
            workspace: './ios/Grazie.xcworkspace',
            export_method: "app-store",
            include_bitcode: false,
            xcargs: "-allowProvisioningUpdates"
        )
    end

    desc 'Distribute to Testflight.'
    lane :distribute do
        pilot(
            app_identifier: "fr.grazie.gigi",
            skip_submission: true,
            skip_waiting_for_build_processing: true
        )
    end
end

platform :android do
    desc 'Build the Android application.'
    lane :build do
        gradle(task: 'clean', project_dir: 'android/')
        gradle(task: 'bundle', build_type: 'Release', project_dir: 'android/')
    end

    desc 'Upload to PlayStore.'
    lane :distribute do
        upload_to_play_store(
            track: 'internal',
            aab: './android/app/build/outputs/bundle/release/app-release.aab'
        )
    end
end