import AuthStateType from './type';

export const authInitialState: AuthStateType = {
  noAuthDatas: {
    config: {
      loading: {
        introHtml: '',
        mediaList: [],
        timer: '',
      },
      onboarding: {
        items: [],
        timer: '',
      },
      gdpr: {
        title: '',
        textHtml: '',
      },
    },
    languages: {
      id: '',
      label: '',
    },
    translation: {
      chooseYourLanguage: '',
      continue: '',
      next:'',
      validate: '',
      skip: '',
      skipStep: '',
      startBtn: '',
      cookiesAccept: '',
      privacyPolicy: '',
      cookiesManage: '',
      termsConditionsAbbr: '',
      //Code Push
      updateInstallMandatory: '',
      updateInstallOptional: '',
      updateMandatoryAvailable: '',
      updateMandatoryAvailableBtn: '',
      yes: '',
      no: '',
      updateAvailable: '',
      updateDownloading: '',
      updateInstalling: '',
      updateInstalled: '',

      onboardingV2Slide1Title: '',
      onboardingV2Slide1Text: '',
      onboardingV2Slide2Title: '',
      onboardingV2Slide3Title: '',
      onboardingV2Slide3Text: '',
    },
  },
  authDatas: {
    translation: {
      register: '',
      logIn: '',
      login: '',
      email: '',
      password: '',
      forgotPasswordQuestion: '',
      notRegisteredAsGigiYet: '',
      registerFormal: '',
      createMyAccount: '',
      confirmPassword: '',
      alreadyRegisteredAsGigi: '',
      loginFormal: '',
      civility: '',
      name: '',
      firstname: '',
      nickname: '',
      godfatherLabel: '',
      godfatherPlaceholder: '',
      godfatherNotExist: '',
      cannotBeYourOwnGodfatherErrorMessage: '',
      nicknameAlreadyExist: '',
      next: '',
      imProfessional: '',
      chooseYourActivity: '',
      helpUsRecommandInfoRelatedActivity: '',
      youWouldRather: '',
      youWouldRatherDescription: '',
      whatDoYouLike: '',
      whatDoYouLikeDescription: '',
      finish: '',
      forgotPassword: '',
      resetPasswordDescription: '',
      resetPassword: '',
      enterYourCode: '',
      codeSentEmailProvided: '',
      didntGetCode: '',
      resendCode: '',
      enterNewPassword: '',
      newPassword: '',
      confirmNewPassword: '',
      savePassword: '',
      newPasswordSaved: '',
      backToLogin: '',
      notifyAllowAllLabel: '',
      notifyEmailLabel: '',
    },
    taxonomy: {
      civilities: [],
      user: {
        proActivities: [],
        profiles: [],
        whishes: [],
      },
    },
  },
};
