name: Create build for both Android and iOS, upload to Google and Apple Store
on: push
jobs:
  # -------------------------------------------------------------
  # ----------------------- ANDROID -----------------------------
  # -------------------------------------------------------------
  

  # -------------------------------------------------------------
  # ------------------------- IOS -------------------------------
  # -------------------------------------------------------------
  build-preprod-ios:
    runs-on: macos-15
    steps:
    # Step 1: Unlock Keychain
    - name: Unlock Keychain
      run: security unlock-keychain -p kristiana /Users/runner/Library/Keychains/login.keychain-db

      