name: Create build for both Android and iOS, upload to Google and Apple Store
on: push
jobs:
  # -------------------------------------------------------------
  # ----------------------- ANDROID -----------------------------
  # -------------------------------------------------------------
  

  # -------------------------------------------------------------
  # ------------------------- IOS -------------------------------
  # -------------------------------------------------------------
  build-preprod-ios:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v3
    # Step 1: Install Node Version 14
    - name: Build and upload to TestFlight
      env:
        GITLAB_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
        PRIVATE_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
      run: echo "${{ secrets.PRIVATE_TOKEN }}"
      