name: Create build for both Android and iOS, upload to Google and Apple Store
on: push
jobs:
  # -------------------------------------------------------------
  # ----------------------- ANDROID -----------------------------
  # -------------------------------------------------------------
  

  # -------------------------------------------------------------
  # ------------------------- IOS -------------------------------
  # -------------------------------------------------------------
  build-preprod-ios:
    runs-on: macos-15
    steps:
    # Step 1: Install Fastlane 
    - name: Install Fastlane
      run:  bundle install
    # Step 2: Unlock Keychain
    - name: Unlock Keychain
      run: security unlock-keychain -p fghj /Users/runner/Library/Keychains/login.keychain-db
    # Step 3: Install Node Version 14
    - name: Build and upload to TestFlight
      env:
        PRIVATE_TOKEN: ${{ secrets.GITLABTOKEN }}
      run: fastlane ios certificates
      